# Generated by Django 5.2.17 on 2026-09-10 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Nazwa usługi / pakietu')),
                ('description', models.TextField(blank=True, verbose_name='Zakres prac / uwagi')),
                ('status', models.CharField(choices=[('PENDING', 'W kolejce'), ('IN_PROGRESS', 'Rozpoczęte'), ('READY', 'Gotowe do wydania'), ('COMPLETED', 'Wydane')], default='PENDING', max_length=20)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota łączna (PLN)')),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Wpłacony zadatek (PLN)')),
                ('scheduled_start', models.DateTimeField(verbose_name='Termin rozpoczęcia')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Faktyczne zakończenie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoatingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coating_product', models.CharField(default='Ceramic Base 9H + Top Coat', max_length=120, verbose_name='Produkt powłoki')),
                ('coating_layers', models.PositiveSmallIntegerField(default=2, verbose_name='Liczba warstw')),
                ('warranty_months', models.PositiveSmallIntegerField(default=36, verbose_name='Gwarancja (miesiące)')),
                ('curing_time_hours', models.PositiveSmallIntegerField(default=24, verbose_name='Czas utwardzania (h)')),
                ('thickness_hood', models.CharField(default='110-130', max_length=30, verbose_name='Maska (µm)')),
                ('thickness_roof', models.CharField(default='100-120', max_length=30, verbose_name='Dach (µm)')),
                ('thickness_trunk', models.CharField(default='105-125', max_length=30, verbose_name='Klapa bagażnika (µm)')),
                ('thickness_doors_left', models.CharField(default='95-115', max_length=30, verbose_name='Drzwi lewe (µm)')),
                ('thickness_doors_right', models.CharField(default='95-115', max_length=30, verbose_name='Drzwi prawe (µm)')),
                ('thickness_fenders', models.CharField(default='100-120', max_length=30, verbose_name='Błotniki (µm)')),
                ('maintenance_guide', models.TextField(default='1. Mycie wyłącznie metodą na dwa wiadra z szamponem o neutralnym pH.\n2. Bezwzględny zakaz korzystania z myjni szczotkowych i agresywnej chemii bezdotykowej.\n3. Pierwsze mycie ręczne możliwe po minimum 14 dniach od aplikacji powłoki.\n4. Wymagany przegląd powłoki oraz dekontaminacja lakieru co 6 miesięcy lub 10 000 km.', verbose_name='Zalecenia serwisowe')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wystawienia')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coating_certificate', to='workshop.serviceorder', verbose_name='Zlecenie detailingowe')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='Numer VIN')),
                ('license_plate', models.CharField(max_length=15, verbose_name='Numer rejestracyjny')),
                ('paint_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kod lakieru')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='workshop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workshop.vehicle'),
        ),
    ]
