# Generated by Django 5.2.17 on 2026-09-10 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_doors_left',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_doors_right',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_fenders',
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_bumper_front',
            field=models.CharField(default='N/D', max_length=30, verbose_name='Zderzak przedni'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_bumper_rear',
            field=models.CharField(default='N/D', max_length=30, verbose_name='Zderzak tylny'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_doors_fl',
            field=models.CharField(default='100-120', max_length=30, verbose_name='Drzwi przednie lewe'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_doors_fr',
            field=models.CharField(default='100-120', max_length=30, verbose_name='Drzwi przednie prawe'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_doors_rl',
            field=models.CharField(default='100-120', max_length=30, verbose_name='Drzwi tylne lewe'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_doors_rr',
            field=models.CharField(default='100-120', max_length=30, verbose_name='Drzwi tylne prawe'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_fenders_front',
            field=models.CharField(default='95-115', max_length=30, verbose_name='Błotniki przednie (L/P)'),
        ),
        migrations.AddField(
            model_name='coatingcertificate',
            name='thickness_fenders_rear',
            field=models.CharField(default='110-130', max_length=30, verbose_name='Błotniki tylne / słupki C'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='coatingcertificate',
            name='maintenance_guide',
            field=models.TextField(default='1. Mycie wyłącznie metodą na dwa wiadra z szamponem o neutralnym pH.\n2. Bezwzględny zakaz korzystania z myjni automatycznych i agresywnej chemii bezdotykowej.\n3. Pierwsze mycie ręczne możliwe po minimum 14 dniach od aplikacji powłoki.\n4. Wymagany przegląd powłoki oraz dekontaminacja lakieru co 6 miesięcy lub 10 000 km.', verbose_name='Zalecenia serwisowe'),
        ),
        migrations.AlterField(
            model_name='coatingcertificate',
            name='thickness_hood',
            field=models.CharField(default='110-130', max_length=30, verbose_name='Maska silnika'),
        ),
        migrations.AlterField(
            model_name='coatingcertificate',
            name='thickness_roof',
            field=models.CharField(default='100-120', max_length=30, verbose_name='Dach'),
        ),
        migrations.AlterField(
            model_name='coatingcertificate',
            name='thickness_trunk',
            field=models.CharField(default='105-125', max_length=30, verbose_name='Klapa bagażnika'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wydania pojazdu'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='deposit_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Zadatek (PLN)'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis / Uwagi'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena całkowita (PLN)'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='scheduled_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Termin wjazdu na halę'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_name',
            field=models.CharField(max_length=128, verbose_name='Pakiet usług'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'W kolejce'), ('IN_PROGRESS', 'Rozpoczęte'), ('READY', 'Gotowe do wydania'), ('COMPLETED', 'Wydane')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workshop.vehicle', verbose_name='Pojazd'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=15, unique=True, verbose_name='Numer rejestracyjny'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=64, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='workshop.customer', verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='paint_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Kod lakieru'),
        ),
    ]
