# Generated by Django 5.2.17 on 2026-09-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_remove_coatingcertificate_thickness_doors_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_bumper_front',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_bumper_rear',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_doors_fl',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_doors_fr',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_doors_rl',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_doors_rr',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_fenders_front',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_fenders_rear',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_hood',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_roof',
        ),
        migrations.RemoveField(
            model_name='coatingcertificate',
            name='thickness_trunk',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='requires_coating_certificate',
            field=models.BooleanField(default=True, verbose_name='Obejmuje aplikację powłoki ceramicznej / certyfikat'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='requires_paint_inspection',
            field=models.BooleanField(default=True, verbose_name='Wymaga inspekcji i pomiaru powłoki lakierniczej (np. Korekta / One-Step)'),
        ),
        migrations.CreateModel(
            name='DamagePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.FloatField(verbose_name='Pozycja X (%)')),
                ('y_pos', models.FloatField(verbose_name='Pozycja Y (%)')),
                ('damage_type', models.CharField(choices=[('CHIP', 'Odprysk od kamienia'), ('SCRATCH', 'Głęboka rysa (do podkładu)'), ('DENT', 'Wgniecenie / wgniotka'), ('REPAINT', 'Ślad powtórnego lakierowania / szpachla'), ('OTHER', 'Inne uszkodzenie')], default='SCRATCH', max_length=20, verbose_name='Typ uszkodzenia')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='Krótka notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_points', to='workshop.serviceorder', verbose_name='Zlecenie')),
            ],
        ),
        migrations.CreateModel(
            name='PaintInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_hood', models.CharField(default='110-130', max_length=30, verbose_name='Maska silnika')),
                ('thickness_roof', models.CharField(default='100-120', max_length=30, verbose_name='Dach')),
                ('thickness_trunk', models.CharField(default='105-125', max_length=30, verbose_name='Klapa bagażnika')),
                ('thickness_bumper_front', models.CharField(default='N/D', max_length=30, verbose_name='Zderzak przedni')),
                ('thickness_bumper_rear', models.CharField(default='N/D', max_length=30, verbose_name='Zderzak tylny')),
                ('thickness_doors_fl', models.CharField(default='100-120', max_length=30, verbose_name='Drzwi przednie lewe')),
                ('thickness_doors_rl', models.CharField(default='100-120', max_length=30, verbose_name='Drzwi tylne lewe')),
                ('thickness_doors_fr', models.CharField(default='100-120', max_length=30, verbose_name='Drzwi przednie prawe')),
                ('thickness_doors_rr', models.CharField(default='100-120', max_length=30, verbose_name='Drzwi tylne prawe')),
                ('thickness_fenders_front', models.CharField(default='95-115', max_length=30, verbose_name='Błotniki przednie (L/P)')),
                ('thickness_fenders_rear', models.CharField(default='110-130', max_length=30, verbose_name='Błotniki tylne / słupki C')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Uwagi do stanu powłoki lakierniczej')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='Data pomiaru')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paint_inspection', to='workshop.serviceorder', verbose_name='Zlecenie')),
            ],
        ),
    ]
