# Generated by Django 5.2.17 on 2026-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_coatingcertificate_thickness_bumper_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagepoint',
            name='car_view',
            field=models.CharField(choices=[('TOP', 'Rzut z góry'), ('LEFT', 'Profil lewy'), ('RIGHT', 'Profil prawy'), ('FRONT', 'Przód pojazdu'), ('REAR', 'Tył pojazdu')], default='TOP', max_length=10, verbose_name='Rzut / Perspektywa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan / Limuzyna'), ('COUPE', 'Coupe / Hatchback 3D'), ('SUV', 'SUV / Kombi / Crossover')], default='SEDAN', max_length=20, verbose_name='Typ nadwozia'),
        ),
        migrations.AlterField(
            model_name='damagepoint',
            name='damage_type',
            field=models.CharField(choices=[('CHIP', 'Odprysk od kamienia'), ('SCRATCH', 'Głęboka rysa (do podkładu)'), ('DENT', 'Wgniecenie / wgniotka'), ('REPAINT', 'Ślad powtórnego lakieru / szpachla'), ('OTHER', 'Inna wada powłoki')], default='SCRATCH', max_length=20, verbose_name='Typ uszkodzenia'),
        ),
    ]
