# Generated by Django 5.2.17 on 2026-09-10 11:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_damagepoint_car_view_vehicle_body_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa produktu')),
                ('category', models.CharField(max_length=64, verbose_name='Kategoria (np. Powłoka, Pasta, Pad)')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stan magazynowy')),
                ('unit', models.CharField(choices=[('ML', 'Mililitry (ml)'), ('PCS', 'Sztuki (szt.)'), ('G', 'Gramy (g)')], default='ML', max_length=8, verbose_name='Jednostka')),
                ('cost_per_unit', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Koszt jednostkowy zakupu netto (PLN)')),
            ],
            options={
                'verbose_name': 'Produkt magazynowy',
                'verbose_name_plural': 'Magazyn chemii i materiałów',
            },
        ),
        migrations.CreateModel(
            name='CarBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64, verbose_name='Marka')),
                ('model', models.CharField(max_length=64, verbose_name='Model')),
                ('svg_code', models.TextField(verbose_name='Kod SVG rzutow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schemat techniczny auta',
                'verbose_name_plural': 'Schematy techniczne aut',
                'unique_together': {('make', 'model')},
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Zużyta ilość')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Zatrzaśnięty koszt jednostkowy (PLN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='workshop.serviceorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='workshop.chemicalproduct')),
            ],
            options={
                'verbose_name': 'Zużycie materiału',
                'verbose_name_plural': 'Zużycie materiałów',
            },
        ),
    ]
