# Generated by Django 5.2.17 on 2026-09-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_chemicalproduct_carblueprint_materialusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'W kolejce'), ('IN_PROGRESS', 'Rozpoczęte'), ('READY', 'Gotowe do wydania'), ('COMPLETED', 'Wydane'), ('CANCELLED', 'Anulowane')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
