# Generated by Django 5.2.17 on 2026-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='requires_coating_certificate',
            field=models.BooleanField(default=False, verbose_name='Obejmuje aplikację powłoki ceramicznej / certyfikat'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='requires_paint_inspection',
            field=models.BooleanField(default=False, verbose_name='Wymaga inspekcji i pomiaru powłoki lakierniczej (np. Korekta / One-Step)'),
        ),
    ]
